### ISSUE TITLE
Don't append new output to existing file

### ISSUE THREAD

**Issue by kiview** [internet-sicherheit/ethereum-cache-creator#28]
The current implementation will add a new JSON array object into the existing file, if file already existing. This leads to broken JSON and therefore can't be a desired behavior. 

There are two alternatives:

1. Append to existing JSON array
2. Use a more complex JSON object as the file root and record each run as a new session
3. Just override the file 

1 sounds wrong and leads to semantically wrong data, so for the sake of simplicity, I'd suggest using solution 3.

**Comment by moekappels** [comment]
ok will focus on 3. should be a relative quick fix. there are also new exercises for school i have to work on.

**Comment by moekappels** [comment]
btw.: did you actually use the same file several times? maybe there is another reason for multiple arrays in the file.

**Comment by kiview** [comment]
> btw.: did you actually use the same file several times? maybe there is another reason for multiple arrays in the file.

I didn't specify different filenames, so the answer should be yes.

**Comment by moekappels** [comment]
ok makes sense. file cannot be found on owncloud. :(

**Comment by kiview** [comment]
I don't know what you are talking about and how this is related to this issue, sorry.

**Comment by moekappels** [comment]
I think this issue was addressed.

**Comment by kiview** [comment]
It is not solved yet but will be once #30 is merged.

**Comment by kiview** [comment]
Fixed by #30.
