### ISSUE TITLE
Add timestamp to transactions

### ISSUE THREAD

**Issue by kiview** [internet-sicherheit/ethereum-cache-creator#29]
Currently we get an ordered list of transactions, however, without the timestamp, it is hard to do a qualitative analysis of this data.

We need to add the timestamp of the transactions to the written file. Best implementation would probably be a UNIX timestamp. 

Do we receive multiple different timestamps when accessing the data via web3?

**Comment by moekappels** [comment]
https://github.com/internet-sicherheit/ethereum-cache-creator/pull/34
